version: '3'
services:
  redis:
      image: redis:alpine
      hostname: redis
      ports:
        - "6379:6379"
  web:
      build: .
      hostname: web
      command : "flask run"
      volumes:
        - .:/app
      ports:
        - "5000:5000"
      environment:
        FLASK_ENV : development
      depends_on:
        - ffmpeg
  ffmpeg:
      image: jrottenberg/ffmpeg
  worker:
      build: .
      command: "celery -A app.celery worker -l info"
      volumes:
        - .:/app
      links:
        - redis
      depends_on:
        - ffmpeg
