version: '3'
services:
  redis:
      container_name: redis
      image: redis:latest
      hostname: redis
  web:
      build: ./app
      hostname: web
      command: ./scripts/run_server.sh
      volumes:
        - ./app:/app
      ports:
        - "5000:5000"
      environment:
      - FLASK_ENV=development
  worker:
      build:
        context: ./app
        dockerfile: Dockerfile
      hostname: worker
      entrypoint: celery
      command: ./scripts/run_celery.sh
      volumes:
        - ./app:/app
      links:
        - redis 
      depends_on:
        - redis
